name: data_analytics
version: "1.0"
config-version: 2

profile: snowflake_profile

require-dbt-version: [">=1.6.0"]

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  data_analytics:
    +materialized: view

    staging:
      +database: DATA_ANALYTICS
      +schema: STG
      +materialized: view

    intermediate:
      +database: DATA_ANALYTICS
      +schema: INT
      +materialized: table

    marts:
      +database: DATA_ANALYTICS
      +schema: MART
      +materialized: table
