version: 2

models:
  - name: stg_orders
    description: "Stage-level cleaned ORDERS from TPCH_SF10"
    columns:
      - name: order_key
        tests:
          - not_null
      - name: cust_key
        tests:
          - not_null
